repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies: []
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]
